### ISSUE TITLE
可否把vscode设置放在项目里

### ISSUE THREAD

**Issue by yanbowe** [nongyehong/HuLa-IM-Tauri#10]
根目录新建.vscode,把项目所需的设置放在setting.json里面，保持配置一致

**Comment by nongyehong** [comment]
我使用的是webstorm开发，并且项目里面使用了.editorconfig来覆盖了设置,并且也使用了eslint和prettier来规范代码，你可以单独在自己的vscode中去使用自己定义的setting.json，该项目没有太多需要setting.json配置的内容
