### ISSUE TITLE
不支持浏览器打开吗？

### ISSUE THREAD

**Issue by yanbowe** [nongyehong/HuLa-IM-Tauri#13]
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/1203eb7a-2426-49b0-9616-0df7beea4587">
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/e810e899-ecda-4742-9c3d-7b934d2e2e92">
浏览器打开白屏，app下什么元素都没有，本地访问地址为http://localhost:6130/

**Comment by yanbowe** [comment]
tauri info

[✔] Environment
    - OS: Mac OS 12.6.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.16.0
    - pnpm: 9.7.1
    - yarn: 1.22.18
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://127.0.0.1:6130/
    - framework: Vue.js
    - bundler: Rollup

**Comment by nongyehong** [comment]
这个项目是桌面程序，没有打算做web端处理，没人会打算桌面端程序代码和web端程序代码写在一起，我觉得这个是不合理的

**Comment by yanbowe** [comment]
> 这个项目是桌面程序，没有打算做web端处理，没人会打算桌面端程序代码和web端程序代码写在一起，我觉得这个是不合理的

好的，有个问题，全屏的话无法完全占满屏幕
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/a323c02d-acfd-4779-90c5-92842e689c8b">

**Comment by nongyehong** [comment]
建议切换dev分支，更新最新的代码，你现在的是windows端的操作栏，最新的代码已经适配了mac
![QQ_1724809364672](https://github.com/user-attachments/assets/70d86f82-1bde-418d-a749-b1bc1a31f3b4)

**Comment by yanbowe** [comment]
> 建议切换dev分支，更新最新的代码，你现在的是windows端的操作栏，最新的代码已经适配了mac ![QQ_1724809364672](https://private-user-images.githubusercontent.com/87641407/362074907-70d86f82-1bde-418d-a749-b1bc1a31f3b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTAyNjcsIm5iZiI6MTcyNDgwOTk2NywicGF0aCI6Ii84NzY0MTQwNy8zNjIwNzQ5MDctNzBkODZmODItMWJkZS00MThkLWE3NDktYjFiYzFhMzFmM2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAxNTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNzkwZDJmNTZjMDg5MGM5ZmExY2VmYTZhMjZkMzkyZmZkNTRkZTEwNWJlMGM1ZjEyOTAwOWQwMmE1OTBiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yZcMsOsm5gs0idYH08Oqk19Ra_Azto2z4VmKpxEoL44)

谢谢，可以了
