### ISSUE TITLE
能否添加苹方字体作为默认字体

### ISSUE THREAD

**Issue by yanbowe** [nongyehong/HuLa-IM-Tauri#15]
因为设计稿普遍是以苹方字体为标准，默认为苹方字体更符合设计规范

**Comment by nongyehong** [comment]
做跨端应用不应该只考虑mac系统下的，我做了一个可以更改字体的功能，我可以理解为你说的是mac系统下默认字体是苹方，win系统下默认黑体这样的功能是可以的

**Comment by yanbowe** [comment]
> 做跨端应用不应该只考虑mac系统下的，我做了一个可以更改字体的功能，我可以理解为你说的是mac系统下默认字体是苹方，win系统下默认黑体这样的功能是可以的

我的想法是按照实际应用来说，苹方字体作为设计师最常用的字体，多端统一的话与设计稿保持一致应该都是苹方字体，所以希望在设置中字体下拉多一个苹方字体的选项

**Comment by nongyehong** [comment]
这个项目设计师也是我，一般在设计软件，比如蓝湖、墨刀这些都是可以设置其他字体，不过普遍是用苹方了，可以设置默认字体为苹方

**Comment by yanbowe** [comment]
> 这个项目设计师也是我，一般在设计软件，比如蓝湖、墨刀这些都是可以设置其他字体，不过普遍是用苹方了，可以设置默认字体为苹方

优秀👍
