### ISSUE TITLE
pnpm run tauri:dev报错

### ISSUE THREAD

**Issue by 982413184** [nongyehong/HuLa-IM-Tauri#3]
Error failed to get cargo metadata: No such file or directory (os error 2)

**Comment by nongyehong** [comment]
或许你遇到了跟这个人一样的问题，这个可能是因为你电脑rust环境引起的：https://github.com/rust-lang/rust-analyzer/issues/3118

**Comment by 9ui** [comment]
thread 'main' panicked at src/common/window.rs:14:10:
Unsupported platform! 'apply_vibrancy' is only supported on macOS: UnsupportedPlatform(""apply_acrylic()" is only supported on Windows.")
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

**Comment by nongyehong** [comment]
@9ui 该问题是
![image](https://github.com/nongyehong/HuLa-IM-Tauri/assets/87641407/5a679593-1949-4ef0-9387-f4242d82980f)
导致的，你可以尝试着把对应的macOS的代码删除。

**Comment by nongyehong** [comment]
拉取最新代码解决这个问题
